import {defineWorkspace} from 'vitest/config'

export default defineWorkspace([
  './packages/models/vitest.config.ts',
  './packages/logger/vitest.config.ts',
  './packages/dogs/vitest.config.ts',
  './packages/schema/vitest.config.ts',
  './packages/mailing/vitest.config.ts',
  './packages/typed-model/vitest.config.ts',
  './packages/helpers/vitest.config.ts',
  './packages/file-manager/vitest.config.ts',
  './packages/graphql/vitest.config.ts',
  './packages/telemetry/vitest.config.ts',
  './packages/components/vitest.config.ts',
  './packages/resolvers/vitest.config.ts',
  './packages/http/vitest.config.ts',
  './packages/echoes/vitest.config.ts',
  './packages/env/vitest.config.ts',
  './packages/crypto/vitest.config.ts',
  './packages/core/vitest.config.ts',
  './packages/mongodb/vitest.config.ts',
  './packages/migrations/vitest.config.ts',
  './packages/cache/vitest.config.ts',
  './packages/paginated-mongodb/vitest.config.ts',
])
